# This fetches a TSV file from Impfdashboard.de, extracts the relevant data and stores it as JSON
# It runs every 2 hours, and if there were changes they will be committed.

name: Generate Data

on:
  schedule:
    - cron:  '15 */2 * * *'

  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  generate data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Set up locale
        uses: sarisia/setup-icu@v1
      - name: Generate Data
        uses: ./actions/generate_data/
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Data
          file_pattern: data/*
