# This is a basic workflow to help you get started with Actions

name: Generate Data

on:
  schedule:
    - cron:  '15 */2 * * *'

  workflow_dispatch:

jobs:
  generateData:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev && npm install canvas --build-from-source     
      - name: Generate Data
        uses: ./
        
