# This is a basic workflow to help you get started with Actions

name: Generate Data

on:
  schedule:
    - cron:  '15 */2 * * *'

  workflow_dispatch:

jobs:
  generateData:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Data
        uses: ./
